Repository Foundation-19/Big-Iron, pull requests merged in 2023-02, with the labels that each got.

#169 Removes fluff railings which have density from the BoS base
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
Labels: bug fix, Mapping

#187 Fixes HE Grenades
  code/game/objects/items/grenades/f13grenade.dm
Labels: bug fix

#195 Fixes Centurion armor having no wound prot
  code/modules/clothing/suits/heavy_armor.dm
Labels: balance

#196 The Thompson Contender
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/modules/projectiles/boxes_magazines/internal/revolver.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  icons/fallout/objects/guns/ballistic.dmi
  icons/obj/guns/projectile.dmi
Labels: Feature

#182 glass takes time to build now + other nerfs
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/structures/window.dm
Labels: balance

#175 readds traders and adds quenching, chickens and other changes
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
Labels: Bug Fix, Mapping, Approved Review

#204 Mapfix
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
Labels: Bug Fix, Mapping

#81 Lucium's beret nerf
  code/modules/clothing/head/f13factionhead.dm
Labels: Test Merged, Awaiting Input, Balance, Approved Review

#117 Revert "Camp Duty and Enclave fix"
  code/__DEFINES/jobs.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/cards_ids.dm
  code/modules/clothing/under/f13.dm
  code/modules/jobs/job_types/legion.dm
Labels: Test Merged, Awaiting Input, Flavor Town, Approved Review

#121 Furnabuse
  modular_BD2/blacksmith/code/furnace.dm
Labels: Test Merged, Bug Fix, Approved Review

#127 port cargo stuff from AB
  code/datums/materials/basemats.dm
  code/modules/cargo/exports/large_objects.dm
  code/modules/cargo/exports/materials.dm
  code/modules/cargo/exports/misc_export.dm
  code/modules/cargo/packs/emergency.dm
  code/modules/cargo/packs/engine.dm
  code/modules/cargo/packs/engineering.dm
  code/modules/cargo/packs/livestock.dm
  code/modules/cargo/packs/materials.dm
  code/modules/cargo/packs/medical.dm
  code/modules/cargo/packs/misc.dm
  code/modules/cargo/packs/organic.dm
  code/modules/cargo/packs/science.dm
  code/modules/cargo/packs/security.dm
  code/modules/cargo/packs/service.dm
  code/modules/cargo/packs/vending.dm
  fortune13.dme
Labels: Test Merged, Balance, Port, Approved Review

#128 Makes Legion Explorers Lore Accurate
  code/modules/jobs/job_types/legion.dm
Labels: Test Merged, Awaiting Input, Balance, Approved Review

#139 NCR Uniform regs
  code/modules/fallout/obj/manual/ncr/ncr_job_guide.dm
  code/modules/jobs/job_types/ncr.dm
Labels: Test Merged, Feature, Approved Review

#191 Chicken deepths
  code/__DEFINES/LivestockFood.dm
  code/game/objects/items/tools/weldingtool.dm
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/food_and_drinks/food/snacks_egg.dm
  code/modules/holiday/easter.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/mob.dm
  code/modules/ruins/icemoonruin_code/library.dm
  fortune13.dme
  icons/fallout/mobs/animals/farmanimals.dmi
  icons/obj/food/food.dmi
  icons/obj/objects.dmi
  modular_BD2/blacksmith/code/finished_items.dm
Labels: Test Merged, Feature, Approved Review

#189 NCR BASE + HMGs
  _maps/map_files/Pahrump/Pahrump-Above-3.dmm
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
  code/_onclick/drag_drop.dm
  code/game/machinery/doors/unpowered.dm
  code/game/objects/structures/HMG.dm
  code/modules/mob/living/simple_animal/hostile/f13/wastebots.dm
  code/modules/research/designs/ammolathe_designs.dm
  fortune13.dme
  icons/fallout/mobs/robots/protectrons.dmi
  icons/obj/HMG.dmi
Labels: Mapping, Feature, Approved Review

#202 Fixes loot
  code/game/objects/effects/spawners/f13lootdrop.dm
Labels: Awaiting Input, Balance, Approved Review

#201 Debug outfit upgrade
  code/game/objects/items/granters.dm
  code/modules/clothing/outfits/standard.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/power/cell.dm
Labels: Feature, Approved Review

#192 Removes RCD and plumping from RND
  code/modules/research/techweb/all_nodes.dm
  code/modules/research/techweb/nodes/engineering_nodes.dm
  code/modules/research/techweb/nodes/medical_nodes.dm
Labels: Awaiting Input, Grudgecode🧂, Feature Removal, Approved Review

#213 readds lost vendors and delete bad ncr spawn
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
Labels: Bug Fix, Mapping

#138 Fixes an R&D exploit
  code/modules/research/techweb/_techweb_node.dm
Labels: Bug Fix, Changes Requested, Approved Review

#174 Nerfs the Brotherhood of Steel, at request of God
  code/modules/jobs/job_types/bos.dm
Labels: Awaiting Input, Balance, Approved Review

#198 Fixes Armor Kit stats
  code/modules/clothing/suits/f13armor.dm
Labels: Test Merged, Balance, Changes Requested, Approved Review

#199 Nerfs Outlaw loadouts
  code/modules/jobs/job_types/wasteland.dm
Labels: Test Merged, Balance, Approved Review

#200 M1 Carbine removes autosear or recoil comp
  code/modules/projectiles/guns/ballistic/automatic.dm
Labels: Balance, Approved Review

#207 Nerfs Flamer
  code/modules/projectiles/guns/ballistic/flamethrower.dm
  code/modules/projectiles/projectile/bullets/shotgun.dm
Labels: Test Merged, Awaiting Input, Balance, Approved Review

#193 Revert "nerfs / fixes the plasmusket"
  code/modules/projectiles/ammunition/caseless/_caseless.dm
  code/modules/projectiles/guns/hoboguns.dm
Labels: Test Merged, Awaiting Input, Balance

#210 Craftable jukeboxes
  code/controllers/subsystem/jukeboxes.dm
  code/game/machinery/dance_machine.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/game/objects/items/stacks/crafting.dm
  code/modules/WVM/items.dm
  code/modules/client/client_procs.dm
  code/modules/research/designs/autolathe_designs.dm
  code/modules/research/designs/autolathe_desings/autolathe_designs_tcomms_and_misc.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/machines/disk_recorder.dmi
  sound/effects/disk_tray.ogg
  sound/effects/plastic_click.ogg
  sound/effects/record_shatter.ogg
  tgui/packages/tgui/interfaces/Jukebox.js
  tgui/public/tgui.bundle.js
Labels: Feature, Approved Review

#211 Kebabism (Town Rework)
  _maps/map_files/Pahrump/Pahrump-Above-3.dmm
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
  code/__DEFINES/access.dm
  code/__DEFINES/jobs.dm
  code/__DEFINES/preferences.dm
  code/datums/components/crafting/recipes/recipes_misc.dm
  code/datums/datacore.dm
  code/game/machinery/doors/unpowered.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/cards_ids.dm
  code/modules/jobs/job_types/kebab.dm
  code/modules/jobs/job_types/merchant.dm
  code/modules/jobs/job_types/rustwalker.dm
  code/modules/jobs/jobs.dm
  fortune13.dme
Labels: Test Merged, Merge Conficts, Mapping, Balance, Feature, Changes Requested
