Repository Foundation-19/Big-Iron, pull requests merged in 2023-03, with the labels that each got.

#250 runtimes fixes: revenge of the sith
  code/__DEFINES/DNA.dm
  code/datums/elements/art.dm
  code/datums/mutations/actions.dm
  code/game/objects/items/dna_injector.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/turfs/change_turf.dm
  code/modules/fallout/obj/campfire.dm
  code/modules/hydroponics/grown/towercap.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/surgery/organic_steps.dm
  code/modules/surgery/surgery_step.dm
  icons/fallout/mobs/animals/farmanimals.dmi
Labels: Bug Fix, Approved for Testmerge

#257 Nerfs Brush Gun, AC Spawner nerf, Vet Decanus helmet buff, RCA melee nerf, Magnum Buckshot removal from Legion/BoS
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/game/objects/effects/spawners/themed_loot_tables.dm
  code/game/objects/items/granters.dm
  code/modules/clothing/head/f13factionhead.dm
  code/modules/clothing/suits/f13armor.dm
  code/modules/jobs/job_types/bos.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/projectiles/guns/ballistic/rifle.dm
Labels: Balance, Approved for Testmerge

#247 Adds MAJ pin, sprite fixes, NCR updates
  code/modules/clothing/under/accessories.dm
  code/modules/fallout/obj/structures/billboard.dm
  code/modules/jobs/job_types/ncr.dm
Labels: Flavor Town, Balance, Approved for Testmerge

#258 makes adamantine/pre-war steel more expensive
  code/modules/cargo/exports/materials.dm
Labels: Bug Fix, Balance, Approved for Testmerge

#246 Removing weather because of crashes
  code/controllers/subsystem/processing/weather.dm
  code/datums/mutations/actions.dm
  code/datums/weather/weather.dm
  code/datums/weather/weather_types/acid_rain.dm
  code/datums/weather/weather_types/ash_storm.dm
  code/datums/weather/weather_types/cold_wave.dm
  code/datums/weather/weather_types/floor_is_lava.dm
  code/datums/weather/weather_types/heat_wave.dm
  code/datums/weather/weather_types/radiation_storm.dm
  code/datums/weather/weather_types/rain.dm
  code/datums/weather/weather_types/snow_storm.dm
  code/game/area/areas.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/secrets.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/events/radiation_storm.dm
  code/modules/events/wizard/lava.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/legion.dm
Labels: Bug Fix, Approved for Testmerge

#245 Better Betterer Blackwater (Budget Goodsprings PR)
  _maps/map_files/Pahrump/Pahrump-Above-3.dmm
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
  code/__DEFINES/jobs.dm
  code/__DEFINES/radio.dm
  code/game/communications.dm
  code/game/machinery/telecomms/machines/bus.dm
  code/game/machinery/telecomms/machines/hub.dm
  code/game/machinery/telecomms/machines/receiver.dm
  code/game/machinery/telecomms/machines/server.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/say.dm
  code/modules/jobs/job_types/wasteland.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/living/say.dm
  interface/stylesheet.dm
  tgui/packages/tgui-panel/chat/constants.js
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
Labels: Test Merged, Mapping, Feature, Approved for Testmerge

#259 Revert "quick service rifle buff"
  code/modules/projectiles/guns/ballistic/automatic.dm
Labels: Balance, Approved for Testmerge

#262 fixes brahmin collar exploit
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
Labels: Test Merged, Bug Fix, Approved for Testmerge

#265 cargo munitions nerf
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/modules/cargo/packs/security.dm
Labels: Balance, Feature, Approved for Testmerge

#283 Blackpowder no longer uses all nearby blackpowder to explode
  code/modules/reagents/chemistry/reagents/pyrotechnic_reagents.dm
Labels: Test Merged, Balance, Feature Removal

#264 AC family rebalance
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/research/designs/ammolathe_designs.dm
Labels: Test Merged, Balance, Opinion, Approved for Testmerge

#267 emergency fixes
  code/game/turfs/turf.dm
  code/modules/projectiles/ammunition/_ammunition.dm
Labels: Test Merged, Bug Fix, Approved for Testmerge

#268 Port recorder
  code/controllers/subsystem/jukeboxes.dm
  code/game/machinery/dance_machine.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/game/objects/items/stacks/crafting.dm
  code/modules/WVM/items.dm
  code/modules/client/client_procs.dm
  code/modules/research/designs/autolathe_designs.dm
  code/modules/research/designs/autolathe_desings/autolathe_designs_tcomms_and_misc.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/machines/disk_recorder.dmi
  sound/effects/disk_tray.ogg
  sound/effects/plastic_click.ogg
  sound/effects/record_shatter.ogg
  tgui/packages/tgui/interfaces/Jukebox.js
Labels: Test Merged, Feature, Port, Approved for Testmerge

#272 Nan chemistry fix port
  code/__DEFINES/maths.dm
  code/game/machinery/autolathe.dm
  code/game/objects/items/stacks/stack.dm
  code/modules/reagents/chemistry/holder.dm
Labels: Test Merged, Bug Fix, Port, Approved for Testmerge

#278 tweakas (suggestions wanted)
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/modules/projectiles/projectile/bullets/rifle.dm
  code/modules/projectiles/projectile/bullets/shotgun.dm
Labels: Test Merged, Balance, Approved for Testmerge

#282 fixes a bunch of surgery issues and "oversights"
  code/modules/surgery/advanced/pacification.dm
  code/modules/surgery/advanced/toxichealing.dm
  code/modules/surgery/brain_surgery.dm
  code/modules/surgery/coronary_bypass.dm
  code/modules/surgery/emergency_cardioversion_recovery.dm
  code/modules/surgery/eye_surgery.dm
  code/modules/surgery/graft_synthtissue.dm
  code/modules/surgery/hepatectomy.dm
  code/modules/surgery/implant_removal.dm
  code/modules/surgery/lobectomy.dm
  code/modules/surgery/surgery.dm
Labels: Test Merged, Bug Fix, Balance, Opinion, Approved for Testmerge

#284 Ported Fix for Unsanitized Input in chem_master.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
Labels: Test Merged, Bug Fix, Approved for Testmerge

#287 total catgirl death
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
Labels: Test Merged, Bug Fix, Feature Removal, Approved for Testmerge

#290 Redoes my PRs, removes a lot of bad chems (Including MKUltra)
  code/datums/components/crafting/recipes/recipes_assemblies.dm
  code/modules/fallout/turf/ground.dm
  code/modules/hydroponics/grown/buffalogourd.dm
  code/modules/hydroponics/grown/horsenettle.dm
  code/modules/hydroponics/grown/pinyon.dm
  code/modules/hydroponics/grown/tomato.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/others.dm
  code/modules/reagents/chemistry/recipes/slime_extracts.dm
  modular_citadel/code/modules/reagents/chemistry/recipes/fermi.dm
Labels: Test Merged, Bug Fix, Feature, Approved for Testmerge

#291 Adds the Chinese Assault Rifle to Lootlists
  code/game/objects/effects/spawners/f13lootdrop.dm
Labels: Test Merged, Balance, Approved for Testmerge

#285 FIXES CARGO CREDIT DUPE EXPLOITS (😱)
  code/modules/cargo/packs/materials.dm
  code/modules/cargo/packs/medical.dm
  code/modules/cargo/packs/security.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Test Merged, Bug Fix, Balance, Approved for Testmerge

#286 HMG fixes, tweaks and additions + kills metarush in its near entirety
  _maps/map_files/Pahrump/Pahrump-Above-3.dmm
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
  code/game/objects/structures/HMG.dm
  code/modules/research/designs/ammolathe_designs.dm
  code/modules/vending/engineering.dm
Labels: Test Merged, Awaiting Input, Bug Fix, Mapping, Balance, Approved for Testmerge

#289 Adds horses to the map + Fixes them
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/job_types/ncr.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  icons/fallout/clothing/horse_armor.dmi
  icons/fallout/mobs/animals/horse.dmi
  icons/mob/actions/actions_animal.dmi
Labels: Test Merged, Bug Fix, Mapping, Balance, Feature, Approved for Testmerge

#293 mob projectile damage fix
  code/modules/mob/living/simple_animal/hostile/f13/raider.dm
Labels: Test Merged, Bug Fix, Approved for Testmerge

#294 Fixes the VR issue
  code/datums/components/crafting/recipes/recipes_misc.dm
  code/modules/jobs/job_types/bos.dm
Labels: Test Merged, Bug Fix, Approved for Testmerge

#269 Capture the Flag TDM style
  code/controllers/subsystem/job.dm
  code/modules/fallout/obj/capturetheflag.dm
  code/modules/mob/dead/new_player/new_player.dm
  fortune13.dme
  icons/obj/holdableflags.dmi
Labels: Enhancement, Test Merged, Feature, Port, Approved for Testmerge

#298 Custom floor tile name change
  code/controllers/subsystem/materials.dm
Labels: Bug Fix, Approved for Testmerge
