Repository Foundation-19/Big-Iron, pull requests merged in 2024-04, with the labels that each got.

#370 Reverts the changes made for Vertibird testing and bug
  code/game/mecha/combat/phazon.dm
  code/game/mecha/mecha.dm
  code/game/mecha/mecha_actions.dm
  code/modules/mob/mob_movement.dm
Labels: Awaiting Input, Bug Fix, Balance, Approved for Testmerge

#392 Tribal ancient book revamped
  code/game/objects/items/granters.dm
Labels: Awaiting Input, Balance, Approved for Testmerge

#447 Reworks the VR to be TDM only
  _maps/VR/yuma_VR.dmm
  code/modules/projectiles/boxes_magazines/ammo_boxes.dm
  code/modules/research/techweb/nodes/bluespace_nodes.dm
  code/modules/vending/assist.dm
Labels: Mapping, Feature

#470 Behemoth
  _maps/map_files/Pahrump/Dungeons.dmm
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
  code/game/objects/items/stealthboy.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/behemoth.dm
  gamedata/data/logs/bot/bot-.txt
Labels: Awaiting Input, Mapping, Feature, Approved for Testmerge

#433 new vehicles
  code/game/mecha/combat/phazon.dm
  icons/mecha/ambulance.dmi
  icons/mecha/jeep.dmi
  icons/mecha/jeepbos.dmi
  icons/mecha/jeepenclave.dmi
  icons/mecha/legionballoon.dmi
  icons/mecha/pickuptruck-mechanics.dmi
Labels: Flavor Town, Feature

#488 Train new list of small changes
  code/datums/components/crafting/guncrafting.dm
  code/datums/components/crafting/recipes/recipes_tribal.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/computer/camera.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/apc_frame.dm
  code/modules/clothing/suits/f13factionarmor.dm
  code/modules/fallout/obj/structures/wasteplants.dm
  code/modules/fallout/turf/ground.dm
  code/modules/farming/farming_structures.dm
  code/modules/hydroponics/grown/wild_windswom_weed.dm
  code/modules/hydroponics/seed_extractor.dm
  code/modules/mob/living/living_sprint.dm
  code/modules/mob/mob.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/misc/syringe_gun.dm
  fortune13.dme
  icons/fallout/clothing/belts.dmi
  icons/obj/flora/wastelandflora.dmi
  icons/obj/hydroponics/harvest.dmi
Labels: Bug Fix, Balance, Feature

#422 adds bike fixing and lets you change the type of car to fix
  code/datums/components/caltrop.dm
  code/game/mecha/mecha_construction_paths.dm
  code/game/mecha/mecha_parts.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/structures/wrecks.dm
  code/modules/mob/mob.dm
  code/modules/vehicles/speedbike.dm
  code/modules/vehicles/vehicle_key.dm
  icons/effects/effects.dmi
  icons/fallout/vehicles/medium_vehicles.dmi
  icons/obj/bike.dmi
  icons/obj/items_and_weapons.dmi
  icons/obj/vehicles/medium_vehicles.dmi
Labels: Balance, Feature, Approved for Testmerge

#475 Church loadout buffs
  code/modules/clothing/suits/armor.dm
  code/modules/jobs/job_types/church.dm
Labels: Awaiting Input, Balance, Feature, Approved for Testmerge

#489 New Vegas Toxins
  code/modules/fallout/obj/food_and_drinks/food.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  code/modules/reagents/chemistry/recipes/toxins.dm
Labels: Awaiting Input, Balance, Feature, Approved for Testmerge
