Repository Foundation-19/Big-Iron, pull requests merged in 2024-02, with the labels that each got.

#369 Fixes the icons for the forgemaster gloves
  modular_BD2/legio_invicta/icons/icons_legion.dmi
  modular_BD2/legio_invicta/icons/onmob_legion.dmi
Labels: Bug Fix

#361 Kebab Blackwater fusion
  _maps/map_files/Pahrump/Pahrump-Above-3.dmm
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
  code/game/objects/effects/landmarks.dm
  code/modules/jobs/job_types/kebab.dm
  code/modules/jobs/job_types/wasteland.dm
  code/modules/jobs/jobs.dm
Labels: Mapping, Feature

#373 Combat & Reinforced Combat Armor buffs/fix
  code/modules/clothing/head/f13head.dm
  code/modules/clothing/suits/f13armor.dm
Labels: Bug Fix, Balance

#379 Fiddles with the south Kebabtown bar (the one with the lathe)
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
Labels: Bug Fix, Mapping

#377 Cleans up compost descriptions
  code/modules/fallout/reagents/other_reagents.dm
Labels: Flavor Town, Bug Fix

#380 Old-New NCR Base + General Area
  _maps/map_files/Pahrump/Pahrump-Above-3.dmm
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
Labels: Enhancement, Mapping, Opinion

#383 Fixes the move up/down verbs
  code/game/atoms_movable.dm
  code/modules/mob/mob_movement.dm
Labels: Test Merged, Bug Fix

#375 Repair old cars
  code/game/mecha/mecha_construction_paths.dm
  code/game/mecha/mecha_parts.dm
  code/game/objects/structures/wrecks.dm
  code/modules/fallout/obj/structures/tires.dm
  code/modules/vehicles/rubbish.dm
  icons/fallout/trash.dmi
  icons/fallout/vehicles/medium_vehicles.dmi
  icons/obj/vehicles/medium_vehicles.dmi
Labels: Enhancement, Sprite

#381 Less loud, Less solid, More efficient, and better initial cell
  code/game/mecha/combat/phazon.dm
  code/game/mecha/mecha.dm
Labels: Bug Fix, Balance

#367 Add files via upload
  code/modules/clothing/head/f13factionhead.dm
  code/modules/fallout/reagents/alcohol.dm
  code/modules/fallout/reagents/juices.dm
  code/modules/fallout/reagents/medicines.dm
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/hydroponics/grown/agave.dm
  code/modules/hydroponics/grown/apple.dm
  code/modules/hydroponics/grown/banana.dm
  code/modules/hydroponics/grown/berries.dm
  code/modules/hydroponics/grown/broc.dm
  code/modules/hydroponics/grown/cereals.dm
  code/modules/hydroponics/grown/citrus.dm
  code/modules/hydroponics/grown/cocoa_vanilla.dm
  code/modules/hydroponics/grown/corn.dm
  code/modules/hydroponics/grown/coyotetobacco.dm
  code/modules/hydroponics/grown/datura.dm
  code/modules/hydroponics/grown/feracactus.dm
  code/modules/hydroponics/grown/flowers.dm
  code/modules/hydroponics/grown/melon.dm
  code/modules/hydroponics/grown/mutfruit.dm
  code/modules/hydroponics/grown/peach.dm
  code/modules/hydroponics/grown/peas.dm
  code/modules/hydroponics/grown/pineapple.dm
  code/modules/hydroponics/grown/pinyon.dm
  code/modules/hydroponics/grown/potato.dm
  code/modules/hydroponics/grown/prickly.dm
  code/modules/hydroponics/grown/pumpkin.dm
  code/modules/hydroponics/grown/punga.dm
  code/modules/hydroponics/grown/root.dm
  code/modules/hydroponics/grown/tato.dm
  code/modules/hydroponics/grown/tea_coffee.dm
  code/modules/hydroponics/grown/tomato.dm
  code/modules/hydroponics/grown/xander.dm
  code/modules/hydroponics/grown/yucca.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
Labels: Enhancement, Flavor Town, Bug Fix

#404 Potential HREF Exploit Fix
  code/modules/admin/verbs/SDQL2/SDQL_2.dm
Labels: Bug Fix, Port

#412 runtime hunting
  code/datums/components/twohanded.dm
  code/datums/traits/_quirk.dm
  code/game/objects/items/grenades/flashbang.dm
  code/game/objects/items/melee/f13twohanded.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/structures/window.dm
  code/modules/clothing/clothing.dm
  code/modules/fallout/misc/gangs.dm
  code/modules/fallout/obj/door_keys.dm
  code/modules/mining/equipment/kinetic_crusher.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/mob.dm
  code/modules/projectiles/guns/ballistic.dm
Labels: Bug Fix
