Repository Foundation-19/Big-Iron, pull requests merged in 2024-03, with the labels that each got.

#413 BCCM Addition
  code/__DEFINES/subsystems.dm
  code/__HELPERS/text.dm
  code/controllers/configuration/configuration.dm
  code/controllers/subsystem/bccm.dm
  code/datums/components/footstep.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/bccm/tgui_asn.dm
  code/modules/admin/bccm/tgui_whitelist.dm
  code/modules/client/client_procs.dm
  config/config.txt
  fortune13.dme
  tgui/packages/tgui/interfaces/BCCMASNPanel.tsx
  tgui/packages/tgui/interfaces/BCCMWhitelistPanel.tsx
  tgui/public/tgui.bundle.js
Labels: Bug Fix, Feature

#362 roaches
  code/modules/mob/living/simple_animal/friendly/cockroach.dm
  code/modules/mob/living/simple_animal/hostile/f13/insects.dm
  icons/fallout/mobs/animals/insects.dmi
  icons/fallout/mobs/animals/roachor.dmi
Labels: Feature, Sprite

#418 Add trunks to the game
  code/__DEFINES/construction.dm
  code/_onclick/adjacent.dm
  code/datums/components/crafting/crafting.dm
  code/datums/components/crafting/recipes/recipes_carparts.dm
  code/datums/components/storage/concrete/trunk.dm
  code/game/mecha/equipment/tools/work_tools.dm
  fortune13.dme
  icons/mecha/mecha_equipment.dmi
Labels: Enhancement

#425 Train's compilation of small changes
  code/__HELPERS/text.dm
  code/controllers/configuration/configuration.dm
  code/controllers/configuration/entries/general.dm
  code/datums/components/crafting/guncrafting.dm
  code/datums/components/footstep.dm
  code/game/objects/structures/beds_chairs/chair.dm
  code/game/objects/structures/wrecks.dm
  code/modules/admin/bccm/tgui_asn.dm
  code/modules/admin/bccm/tgui_whitelist.dm
  code/modules/jobs/job_types/kebab.dm
  code/modules/mob/living/carbon/death.dm
  code/modules/research/designs/misc_designs.dm
  code/modules/vehicles/rubbish.dm
  config/config.txt
  fortune13.dme
  modular_coyote/code/regeneration/_defines/signals_statuseffects.dm
  modular_coyote/code/regeneration/sleepingpart/regenerate_sleeping.dm
Labels: Bug Fix, Balance, Feature

#399 Map Overhaul PR Part 1
  _maps/map_files/Pahrump/Dungeons.dmm
  _maps/map_files/Pahrump/Pahrump-Above-3.dmm
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
  _maps/map_files/generic/CentCom.dmm
  code/modules/clothing/head/f13factionhead.dm
  code/modules/clothing/suits/f13factionarmor.dm
  code/modules/jobs/job_types/enclave.dm
  code/modules/jobs/job_types/kebab.dm
Labels: Enhancement, Bug Fix, Mapping, Balance, Opinion

#417 Legion Armor buffs + NCR Armor buffs + No More Crutch Gun (14mm smg)
  code/__DEFINES/traits.dm
  code/datums/martial/wrestling.dm
  code/game/objects/items/granters.dm
  code/game/objects/items/melee/f13onehanded.dm
  code/game/objects/items/melee/f13powerfist.dm
  code/game/objects/items/melee/f13twohanded.dm
  code/modules/clothing/head/f13factionhead.dm
  code/modules/clothing/suits/f13factionarmor.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/job_types/ncr.dm
  code/modules/jobs/jobs.dm
  code/modules/projectiles/guns/ballistic/rifle.dm
Labels: Enhancement, Bug Fix, Balance

#424 Completely removes Radiation from Tritium
  code/modules/atmospherics/gasmixtures/reactions.dm
Labels: Balance, Feature Removal

#428 Removes smoke machine and cryo casing from R&D, adds the recharger guns
  code/modules/research/designs/weapon_designs.dm
  code/modules/research/techweb/nodes/biotech_nodes.dm
  code/modules/research/techweb/nodes/medical_nodes.dm
  code/modules/research/techweb/nodes/weaponry_nodes.dm
Labels: Enhancement, Balance, Feature Removal

#435 Linters Fix
  _maps/map_files/Pahrump/Pahrump-Above-3.dmm
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  code/game/objects/items/granters.dm
Labels: Bug Fix

#434 Update shotgun.dm
  code/modules/projectiles/projectile/bullets/shotgun.dm
Labels: Balance

#426 New stock parts sprites
  icons/obj/stock_parts.dmi
Labels: Flavor Town, Sprite

#441 Bug Fix: Vendors
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
Labels: Bug Fix, Mapping

#421 Adds two new quirks: Deaf and Tongue-tied
  code/__DEFINES/_flags/item_flags.dm
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/datums/components/crafting/recipes/recipes_clothing.dm
  code/datums/traits/negative.dm
  code/datums/traits/neutral.dm
  code/game/objects/items/devices/radio/radio.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/mob/living/carbon/say.dm
  code/modules/mob/living/say.dm
  code/modules/surgery/organ_manipulation.dm
  code/modules/surgery/organs/tongue.dm
  icons/mob/clothing/hands.dmi
  icons/obj/clothing/gloves.dmi
Labels: Flavor Town, Feature

#443 Trainshot Tweaks
  code/modules/projectiles/projectile/bullets/shotgun.dm
Labels: Balance

#437 5 second PR to fix legion casino cheese
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
Labels: Mapping

#446 cuts trainshot's AP in half
  code/modules/projectiles/projectile/bullets/shotgun.dm
Labels: Balance

#436 Funny Martial Arts Update per Request
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/job_types/ncr.dm
Labels: Awaiting Input, Balance, Approved for Testmerge

#456 Makes eels unobtainable
  code/game/objects/items/fishingrod.dm
Labels: Awaiting Input, Grudgecode🧂, Feature Removal, Approved for Testmerge

#454 Reverts Rocket Launcher Grudgecode
  code/datums/components/crafting/recipes/recipes_explosives.dm
Labels: Awaiting Input, Balance, Approved for Testmerge

#455 Balances Gauss rifle so it's not a two-shot through PA
  code/modules/projectiles/guns/ballistic/automatic.dm
Labels: Awaiting Input, Balance, Grudgecode🧂, Approved for Testmerge

#458 barkeep spawn and fruttyntaurious spawn fix
  code/game/objects/effects/landmarks.dm
  code/modules/jobs/job_types/kebab.dm
  code/modules/jobs/jobs.dm
Labels: Bug Fix, Approved for Testmerge

#440 Removes Enclave roundstart NVGs
  code/modules/jobs/job_types/enclave.dm
Labels: Awaiting Input, Balance, Approved for Testmerge

#391 Additions+Bug Fixes: Tarkov is gone & backpack additions.
  code/_globalvars/lists/flavor_misc.dm
  code/controllers/subsystem/job.dm
  code/game/objects/items/storage/backpack.dm
  code/modules/hydroponics/grown/cotton.dm
  icons/mob/clothing/back.dmi
  icons/mob/inhands/equipment/backpack_lefthand.dmi
  icons/mob/inhands/equipment/backpack_righthand.dmi
  icons/obj/storage.dmi
  modular_citadel/code/modules/client/loadout/_loadout.dm
  modular_citadel/code/modules/client/loadout/backpack.dm
Labels: Awaiting Input, Bug Fix, Approved for Testmerge

#431 blacklist some items from the board gacha
  code/game/objects/structures/wrecks.dm
Labels: Awaiting Input, Balance, Approved for Testmerge

#467 CQC Death
  code/modules/jobs/job_types/ncr.dm
Labels: Balance

#438 Reduces the Khans to a loadout, Re-adds the Den faction
  _maps/map_files/Pahrump/Pahrump-Above-3.dmm
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
  code/__DEFINES/jobs.dm
  code/__DEFINES/radio.dm
  code/game/communications.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/modules/clothing/under/f13.dm
  code/modules/fallout/misc/gang_items.dm
  code/modules/fallout/misc/gangs.dm
  code/modules/jobs/job_types/wasteland.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/living/say.dm
  fortune13.dme
  modular_citadel/code/modules/client/loadout/backpack.dm
  modular_citadel/code/modules/client/loadout/head.dm
  modular_citadel/code/modules/client/loadout/shoes.dm
  modular_citadel/code/modules/client/loadout/uniform.dm
Labels: Enhancement, Awaiting Input, Mapping, Feature Removal, Approved for Testmerge

#464 Legion Loadout buff
  code/modules/jobs/job_types/legion.dm
Labels: Balance

#374 removing hardstuns from silicons
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Awaiting Input, Balance, Approved for Testmerge, Copecode 🥺

#465 Ncr loadout balance + faction armor buffs
  code/modules/clothing/head/f13factionhead.dm
  code/modules/clothing/suits/f13factionarmor.dm
  code/modules/jobs/job_types/ncr.dm
  icons/fallout/clothing/armored_medium.dmi
  icons/fallout/clothing/hats.dmi
  icons/fallout/onmob/clothes/armor_medium.dmi
  icons/fallout/onmob/clothes/head.dmi
Labels: Balance

#457 Adds small details to make a previously unknown dungeon more visible
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
Labels: Awaiting Input, Mapping, Approved for Testmerge

#461 Ports explosive arrows from Lonestar
  code/datums/components/crafting/recipes/recipes_primal.dm
  code/modules/projectiles/ammunition/caseless/arrow.dm
  code/modules/projectiles/projectile/reusable/arrow.dm
  icons/fallout/objects/guns/ammo.dmi
Labels: Feature

#469 service rifle & R82 buff + hunting rifle slappage
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/rifle.dm
Labels: Balance, Grudgecode🧂

#473 Fixes the Vex Nightstalker Pelt Sprite
  icons/fallout/clothing/hats.dmi
  icons/fallout/onmob/clothes/head.dmi
Labels: Bug Fix, Sprite

#345 add old rusty to tribal loadout
  code/modules/jobs/job_types/wasteland.dm
Labels: Awaiting Input, Balance, Approved for Testmerge

#466 Melee buffs
  code/game/objects/items/melee/f13onehanded.dm
  code/game/objects/items/melee/f13powerfist.dm
  code/game/objects/items/melee/f13twohanded.dm
Labels: Balance

#471 Rubber bullet nerf
  code/modules/projectiles/projectile/bullets/pistol.dm
  code/modules/projectiles/projectile/bullets/rifle.dm
Labels: Grudgecode🧂
